GET http://127.0.0.1:8080/api/FreightExchange/

###

GET http://127.0.0.1:8080/api/Users/

###

POST http://127.0.0.1:8080/api/FreightExchange/
Content-Type: application/json

{
  "name": "Testm",
  "email": "Testm"
}