GET http://127.0.0.1:8080/api/FreightExchange/

###

GET http://127.0.0.1:8080/api/Users/

###

POST http://127.0.0.1:8080/api/FreightExchange/
Content-Type: application/json

{
  "name": "Testm",
  "email": "Testm"
}

###

POST http://127.0.0.1:8080/api/CartageErrands/1/Offers
Content-Type: application/json

{
  "BidderId": "1",
  "Price": "10"
}

###
POST http://127.0.0.1:8080/api/CartageErrands/
Content-Type: application/json

{
  "founderId": 1,
  "goodsName": "P³ytki",
  "startingAdress": "Radom",
  "destinationAdress": "Bia³ystok",
  "distance": 300,
  "weight": 12,
  "maximumPrice": 1000,
  "endDate": "2024-04-25T09:52:28.112Z"
}
